//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("exxeleron")]
[assembly: System.Reflection.AssemblyTitle("qSharp: TickClient")]
[assembly: System.Reflection.AssemblyProduct("qSharp")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © exxeleron 2011-2014")]
[assembly: System.Reflection.AssemblyVersion("2.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.0.0")]


