//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCompany("exxeleron")]
[assembly: System.Reflection.AssemblyTitle("qSharp: Publisher")]
[assembly: System.Reflection.AssemblyProduct("qSharp")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © exxeleron 2011-2015")]
[assembly: System.Reflection.AssemblyVersion("2.2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("2.2.0.0")]


